site_name: pyjelly
site_description: Jelly RDF implementation for Python
site_url: https://jelly-rdf.github.io/en/latest/
repo_name: Jelly-RDF/pyjelly
repo_url: https://github.com/Jelly-RDF/pyjelly
edit_uri: edit/main/docs/
watch:
- pyjelly

nav: []

theme:
  name: material
  features:
  - announce.dismiss
  - header.autohide
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode

extra_css:
- css/mkdocstrings.css

markdown_extensions:
- admonition
- footnotes
- pymdownx.emoji
- codehilite
- pymdownx.magiclink
- pymdownx.superfences
- md_in_html
- mdx_include:
    base_path: docs/
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.highlight:
    use_pygments: true
- toc:
    permalink: true

plugins:
- search
- autorefs
- markdown-exec
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          heading_level: 3
          # https://mkdocstrings.github.io/python/usage/#configuration/
          docstring_style: numpy
          docstring_section_style: list
          docstring_options:
            ignore_init_summary: true
            trim_doctest_flags: false
          members_order: source
          merge_init_into_class: true
          parameter_headings: true
          show_submodules: true
          show_inheritance_diagram: false
          show_signature_annotations: false
          signature_crossrefs: true
          line_length: 60
          show_labels: false
          show_symbol_type_heading: false
          show_symbol_type_toc: true
          summary: true
        paths: [pyjelly/]
        inventories:
        - http://docs.python.org/3/objects.inv
