# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_pb2 as grpc__pb2
import rdf_pb2 as rdf__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RdfStreamServiceStub(object):
    """Pub/Sub service for RDF streams, to be implemented by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeRdf = channel.unary_stream(
                '/eu.ostrzyciel.jelly.core.proto.v1.RdfStreamService/SubscribeRdf',
                request_serializer=grpc__pb2.RdfStreamSubscribe.SerializeToString,
                response_deserializer=rdf__pb2.RdfStreamFrame.FromString,
                _registered_method=True)
        self.PublishRdf = channel.stream_unary(
                '/eu.ostrzyciel.jelly.core.proto.v1.RdfStreamService/PublishRdf',
                request_serializer=rdf__pb2.RdfStreamFrame.SerializeToString,
                response_deserializer=grpc__pb2.RdfStreamReceived.FromString,
                _registered_method=True)


class RdfStreamServiceServicer(object):
    """Pub/Sub service for RDF streams, to be implemented by the server.
    """

    def SubscribeRdf(self, request, context):
        """Subscribe to an RDF stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishRdf(self, request_iterator, context):
        """Publish an RDF stream.
        In case the server cannot process the stream, it must respond with
        the INVALID_ARGUMENT error.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RdfStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeRdf': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeRdf,
                    request_deserializer=grpc__pb2.RdfStreamSubscribe.FromString,
                    response_serializer=rdf__pb2.RdfStreamFrame.SerializeToString,
            ),
            'PublishRdf': grpc.stream_unary_rpc_method_handler(
                    servicer.PublishRdf,
                    request_deserializer=rdf__pb2.RdfStreamFrame.FromString,
                    response_serializer=grpc__pb2.RdfStreamReceived.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eu.ostrzyciel.jelly.core.proto.v1.RdfStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eu.ostrzyciel.jelly.core.proto.v1.RdfStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RdfStreamService(object):
    """Pub/Sub service for RDF streams, to be implemented by the server.
    """

    @staticmethod
    def SubscribeRdf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/eu.ostrzyciel.jelly.core.proto.v1.RdfStreamService/SubscribeRdf',
            grpc__pb2.RdfStreamSubscribe.SerializeToString,
            rdf__pb2.RdfStreamFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishRdf(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/eu.ostrzyciel.jelly.core.proto.v1.RdfStreamService/PublishRdf',
            rdf__pb2.RdfStreamFrame.SerializeToString,
            grpc__pb2.RdfStreamReceived.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
