#!/usr/bin/env bash

# shellcheck disable=SC2120
compile-pb2() {
    local PROTO_PATH=${1:-"pyjelly/_protocol"}
    local OUT_DIR=${2:-"pyjelly/pb2"}

    command mkdir -p "$OUT_DIR"
 
    : Compiling rdf.proto...
    python -m grpc_tools.protoc "$PROTO_PATH/rdf.proto" --proto_path="$PROTO_PATH" --{python,pyi}_out="$OUT_DIR"
 
    : Compiling grpc.proto...
    python -m grpc_tools.protoc "$PROTO_PATH/grpc.proto" --proto_path="$PROTO_PATH" --{python,pyi,grpc_python}_out="$OUT_DIR"
 
    : Done
}

[[ "${BASH_SOURCE[0]}" == "$0" ]] && set -CETeuxo pipefail && compile-pb2
